version: "3.8"
services:
  uniswap-hft-api:
    build:
      context: .
    container_name: uniswap-hft-api
    volumes:
      - .:/docker-app
    ports:
      - "${PORT}:${PORT}"
    command: 
      - "python"
      - "app.py"
      - "${CEX_OR_DEX}"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${PORT}/healthcheck || exit 1"]
      interval: 15m
      timeout: 30s
      retries: 5
      start_period: 15s
    networks:
      - uniswap-hft-network

  uniswap-hft-scheduler:
    build:
      context: .
    container_name: uniswap-hft-scheduler
    command: 
      - "python"
      - "-m"
      - "uniswap_hft.scheduler.scheduler"
    networks:
      - uniswap-hft-network
    depends_on:
      - uniswap-hft-api

  uniswap-hft-telegram-bot:
    build:
      context: .
    container_name: uniswap-hft-telegram-bot
    command: 
      - "python"
      - "-m"
      - "uniswap_hft.telegram_interface.telegram_handler"
    networks:
      - uniswap-hft-network
    depends_on:
      - uniswap-hft-api

networks:
  uniswap-hft-network:
    driver: bridge