version: "3.8"
services:
  uniswap-hft-api:
    build:
      context: .
    image: acrtradingdeskdev.azurecr.io/trading-engine/uniswap-hft:${TAG}
    container_name: uniswap-hft-api
    env_file: 
      - "${ENV_FILE}"
    volumes:
      - ./${POSITION_HISTORY_PATH}:/docker-app/${POSITION_HISTORY_PATH}
    ports:
      - "${PORT}:${PORT}"
    command: 
      - "python"
      - "app_${CEX_OR_DEX}.py"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${PORT}/healthcheck || exit 1"]
      interval: 15m
      timeout: 30s
      retries: 5
      start_period: 15s
    networks:
      - uniswap-hft-network
    logging:
        driver: "json-file"
        options:
            max-size: "25m"
            max-file: "10"
            
  uniswap-hft-scheduler:
    build:
      context: .
    image: acrtradingdeskdev.azurecr.io/trading-engine/uniswap-hft:${TAG}
    container_name: uniswap-hft-scheduler
    env_file: 
      - "${ENV_FILE}"
    command: 
      - "python"
      - "-m"
      - "uniswap_hft.scheduler.scheduler"
    networks:
      - uniswap-hft-network
    depends_on:
      - uniswap-hft-api
    logging:
        driver: "json-file"
        options:
            max-size: "25m"
            max-file: "10"

  uniswap-hft-telegram-bot:
    build:
      context: .
    image: acrtradingdeskdev.azurecr.io/trading-engine/uniswap-hft:${TAG}
    container_name: uniswap-hft-telegram-bot
    env_file: 
      - "${ENV_FILE}"
    command: 
      - "python"
      - "-m"
      - "uniswap_hft.telegram_interface.telegram_handler"
    networks:
      - uniswap-hft-network
    depends_on:
      - uniswap-hft-api
    logging:
        driver: "json-file"
        options:
            max-size: "25m"
            max-file: "10"

networks:
  uniswap-hft-network:
    driver: bridge